name: Cleanup Cloudflare Pages Deployments
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Cloudflare Pages Deployments
        uses: Th3S4mur41/cleanup-cloudflare-deployments@82ff2b17411f784e4c5f28ff56cbefdf51020cf0
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ secrets.CLOUDFLARE_PAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cleanup-types: all
          production-keep: 5
